### ISSUE TITLE
Failed to launch

### ISSUE THREAD

**Issue by w9smith** [micahmo/WireGuardServerForWindows#5] opened 2021-09-27 05:11 UTC
Greetings
Thank you for making WG4W.  I can not get it to launch.

My setup
Edition	Windows 10 Pro
Version	21H1
OS build	19043.1237
Experience	Windows Feature Experience Pack 120.2212.3530.0
CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.20 GH
RAM: 8GB

WinGuard - downloaded, install
WG4W - download portable, unzip, launch 'WireGuardServerForWindows.exe'
Installed the .Net Core when prompted
.NetCore gives install complete dialog box
Get error that .NetCore is not installed. I see it in the installed program list.
Did repair of .NetCore.
Launch WireGuardServerForWindows.exe, same error
Restart computer
Launch WireGuardServerForWindows.exe, same error
![step01](https://user-images.githubusercontent.com/58622495/134848235-fec46d74-2478-4e83-ae14-0b9b7259bfb6.png)
![step02](https://user-images.githubusercontent.com/58622495/134848243-5b3af130-19da-45fb-b19a-6f60869787f1.png)

Any suggestions would be appreciated.
Thank you

**Comment by micahmo** [comment] 2021-09-27 12:18
Hi @w9smith, I apologize that you are experiencing this issue. I will try to reproduce on a clean Win 10 21H1 VM and get back to you. Thanks for reporting!

**Comment by micahmo** [comment] 2021-09-27 21:08
Hi @w9smith, I believe the issue is that you downloaded the base .NET Core 3.1 Runtime instead of the .NET Core Desktop Runtime. It's not your fault; the Windows error message does not indicate which version you should download.

Can you please try downloading and installing the x64 .NET Core Desktop Runtime and report back? If that works, I will update the README with the appropriate instructions. I would also like to add an enhancement for a proper installer to the backlog, to prevent these kinds of issues in the future.

![image](https://user-images.githubusercontent.com/7417301/134985502-f5967b3d-3661-46a3-bfaa-02c447032f23.png)

**Comment by w9smith** [comment] 2021-10-05 06:43
Hi
That was the issue.  I installed the wrong .NET package.  When I installed the correct .NET package your program worked.
The tunnel is up and running.

I am testing on a single subnet. 

Tunnel is running


But I can not ping opposite ends of tunnel. 
I can not ping computers across tunnel. 
Edge browser times out on client side.
If I deactivate the client-peer, Internet access works normally. I know the  0.0.0.0/0 is routing all client-peer traffic.  So it appears it is a wireguard issue.

I have disable firewalls and antivirus on both computers (i.e. server peer and client peer).
I moved the client-peer out of my network.  I used the cell phone to give it a not-my-internet connection.
Same issues.

A Google search did not help me resolve the issue.  Since I only need one-computer-to-one-computer tunnel; I will go back to SSH with public/private keys for this project.  I am running out of time.  But I would like to learn more about WireGuard and try to understand why I could not get it to work.  Do you have any suggestions?



Best wishes
WS

**Comment by micahmo** [comment] 2021-10-05 11:59
> That was the issue.  I installed the wrong .NET package.  When I installed the correct .NET package your program worked.

Excellent, I'm glad to hear that! I added a [section to the README](https://github.com/micahmo/WireGuardServerForWindows#gui) about that, and I've also created a new enhancement (#6) to create a proper installer in the future.

Sorry to hear that WireGuard is still not working for you. From what I've seen, issues generally fall into either connection or routing. When your client connects to your server, check the logs on the server side and verify that there is a `latest handshake` under the peer entry. Without that, nothing else will work. If that's there, check whether the `transfer` amount is increasing as you make requests on the client. Check whether you are sharing the correct network interface that has internet access.

A couple other general tips:
 - Make sure you've configured port forwarding on your router
 - Beware that Internet Sharing can become disabled after a reboot


I will close this issue for now, since we've solved the original question. Feel free to open a new issue for general troubleshooting. If you do, please post your configuration.

**Closed by micahmo** 2021-10-05 11:59 UTC
Labels: documentation, question
