### ISSUE TITLE
Connection stablished but not changing IP

### ISSUE THREAD

**Issue by oppalla** [micahmo/WireGuardServerForWindows#4] opened 2021-07-30 17:56 UTC
Hi! Thanks @micahmo for the amazing WireGuard deployer for Windows.

I've used it to configure a WireGuard Server on a remote Windows Server 2019. But its not hiding the Client IP.

The configuration I used for Server is this: [see screenshot](https://i.ibb.co/0cVd730/image.png) (MYEXTERNALIPADDRESS is substituted by the real IP address)

And the configuration I used for Client is this: [see screenshot](https://i.ibb.co/kJM3Kkq/image.png) (even using 1.1.1.1 as DNS the issue still happen)

When I connect everything, the handkshake is complete, but if I try "what is my ip" on Google, on client side, it still shows the real IP and not the Remote Windows Server 2019 IP.

Am I missing something?

**Comment by micahmo** [comment] 2021-07-31 01:32
Hi @oppalla, thanks for the kind words!

Most likely the problem is related to the addresses that you're routing through the VPN. These are set via the `Allowed IPs` property in the server configuration (not the most intuitive name, but I took all the [terms from WireGuard](https://wiki.archlinux.org/title/WireGuard#:~:text=The%20keyword,to%20the%20peer.)). I see you're only routing `192.168.200.2/32`, meaning that a request on the client to any address outside that range (e.g., "what is my ip" on Google) will get routed through the client's host network instead of the VPN.

If you want every network request on the client to go through the VPN, route `0.0.0.0/0`, like [this](https://user-images.githubusercontent.com/7417301/127724560-8a676414-1e6b-4eba-b976-cb4a289c9373.png).

BTW, it looks like you don't have `Private Network` or `Internet Sharing` enabled, so once you route `0.0.0.0/0` on the client through the VPN, you might find that you completely lose internet access on the client, since the network adapter on the server won't have internet access.

P.S. You might not want to share your private keys online, even if your public IP address is removed. :-)

**Comment by oppalla** [comment] 2021-07-31 02:43
You are the best @micahmo 

I've changed the `Allowed IPs` on Server Configurationa and saved.

I also re-exported the Client Configuration and loaded it on the client machine.

Now, the handshake is made, but internet access don't work from client.

Also, now and before, ping between the machine ips (192.168.200.1 to 192.168.200.2 and vice versa) don't work.

On WS4W everything is checked green, and should be working, but, checking on the "View Server Status", even after reinstalling both, WireGuard and WS4W, it shows under "Peer:" the "allowed ips: 192.168.200.2/32", as if this configuration wasn't refreshed somehow.

[You can check here the screenshot of WS4W showing the "View Server Status"](https://i.ibb.co/hXp2f1S/image.png)

Maybe I'm still missing something?

Thank you so much in advance for your prestative support!

**Comment by micahmo** [comment] 2021-07-31 03:25
> checking on the "View Server Status", even after reinstalling both, WireGuard and WS4W, it shows under "Peer:" the "allowed ips: 192.168.200.2/32", as if this configuration wasn't refreshed somehow.

That is actually correct. `Allowed IPs` has two different meanings depending on whether you're on the server or client. From the perspective of the server, it defines the IP(s) that the client is allowed to connect from. You've configured your client to run under `192.168.200.2`, so that is correct.

However, what I don't see on that status page is any mention of a successful client handshake. For reference, here is my status after my client has connected successfully.

![image](https://user-images.githubusercontent.com/7417301/127726794-0cfd0448-d567-4f17-b1c7-29f623d17340.png)

Just to verify... it looks like your endpoint port is `51810` on your public IP. Have you configured port forwarding on your router to forward UDP traffic from `51810` to your server machine's LAN IP? (I realized I omitted any mention of port forwarding from the README; I will add that.)

**Comment by oppalla** [comment] 2021-07-31 15:07
Thanks @micahmo, I just reinstalled everything, and it sudennly start working.

After I restart my Windows 2019 Server, it will connect but the client not have internet. Then I open up WGS4W and it still shows everything greened out. 

But, I need to manually go to adapter settings, and click and unclick internet sharing again. Then, the client have connection shared from server.

Thanks for troubleshooting, and for developing this amazing tool!

**Comment by micahmo** [comment] 2021-07-31 15:31
Awesome, glad everything's working now!!

> I need to manually go to adapter settings, and click and unclick internet sharing again. Then, the client have connection shared from server.

Right, this is a known issue with internet sharing in Windows. It reports as being enabled (hence why it's green in WS4W and checked in the adapater settings) but it often does not really come back after a restart.

If you want, take a look at [this section](https://github.com/micahmo/WireGuardServerForWindows#known-issues) of the README. You can use the WS4W CLI and Windows Task Scheduler to automatically disable and re-enable internet sharing after a reboot. That should get around the Windows issues.

**Closed by micahmo** 2021-07-31 15:31 UTC
